### ISSUE TITLE
Application Crash with the log  "com.merryjs.PhotoViewer.PhotoViewer.MerryPhotoViewActivity"

### ISSUE THREAD

**Issue by vivekspraxa** [merryjs/photo-viewer#136]
React-native application has been crashed with the logs in crashlytics

Details :- "react-native": "0.63.4",
Gradle-6.2 
"@merryjs/photo-viewer": "3.2.1"

![image](https://user-images.githubusercontent.com/43368887/140898054-9c6659d8-7006-4564-8a41-d5b95a95f1f2.png)

**Comment by bang88** [comment]
Hey @vivekspraxa Did you link it correctly. Please follow the README.md and check it again.

**Comment by RodolfoGS** [comment]
I have the same issue

`react-native: 0.64.2`
`@merryjs/photo-viewer: 3.2.3`

```
Caused by java.lang.ClassNotFoundException: Didn't find class "com.merryjs.PhotoViewer.PhotoViewer.MerryPhotoViewActivity" on path: DexPathList[[zip file "/data/app/_app_name_-2jZYkeUswgPpH1E9K_iXJQ==/base.apk"],nativeLibraryDirectories=[/data/app/_app_name_-2jZYkeUswgPpH1E9K_iXJQ==/lib/x86, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by DodoSpringLove** [comment]
same issue here:
Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.x.g/com.merryjs.PhotoViewer.PhotoViewer.MerryPhotoViewActivity}: java.lang.ClassNotFoundException: Didn't find class "com.merryjs.PhotoViewer.PhotoViewer.MerryPhotoViewActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.instpower.global-dRViLeBp1OA-rwilBXdIPA==/base.apk"],nativeLibraryDirectories=[/data/app/com.i.g-dRViLeBp1OA-rwilBXdIPA==/lib/arm64, /data/app/com.i.g-dRViLeBp1OA-rwilBXdIPA==/base.apk!/lib/arm64-v8a, /system/lib64]]
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2881)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

react-native :
 System: OS: macOS 12.3.1 
CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz 
Memory: 146.79 MB / 16.00 GB Shell: 5.8 - /bin/zsh 
Binaries: Node: 17.0.1 - /usr/local/bin/node 
Yarn: 1.22.17 - /usr/local/bin/yarn 
npm: 8.1.0 - /usr/local/bin/npm 
Watchman: 2021.10.18.00 - /usr/local/bin/watchman 
Managers: CocoaPods: 1.11.3 - /usr/local/bin/pod 
SDKs: iOS 
SDK: Platforms: DriverKit 21.4,iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK: API Levels: 19, 22, 25, 27, 28, 29, 30, 31 
Build Tools: 25.0.2, 25.0.3, 26.0.2, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0 
System Images: android-25 | China version of Android Wear Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64 Android NDK: Not Found IDEs: Android Studio: 4.2 AI-202.7660.26.42.7486908 
Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild 
Languages: Java: 11.0.2 - /usr/bin/javac 
npmPackages: @react-native-community/
cli: Not Found 
react: ^17.0.2 => 17.0.2 react-native: ^0.65.1 => 0.65.2 
react-native-macos: Not Found 
npmGlobalPackages: react-native: Not Found

**Comment by DodoSpringLove** [comment]
have any updates?
