### ISSUE TITLE
Linking failed RN 0.54

### ISSUE THREAD

**Issue by aijason** [merryjs/photo-viewer#67]
(node:4554) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at findLineToAddPod (/Users/hjs/Desktop/cassec-ecapp/node_modules/react-native/local-cli/link/pods/findLineToAddPod.js:21:44)
    at getLinesToAddEntry (/Users/hjs/Desktop/cassec-ecapp/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:32:12)
    at registerNativeModulePods (/Users/hjs/Desktop/cassec-ecapp/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:21:27)
    at Object.registerNativeModule [as register] (/Users/hjs/Desktop/cassec-ecapp/node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:11:5)
    at pollParams.then.params (/Users/hjs/Desktop/cassec-ecapp/node_modules/react-native/local-cli/link/link.js:64:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:4554) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4554) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bang88** [comment]
Maybe the error are from `react-native link ` itself not  this library. please update your react native cli and try again. It works on my side.
